import sys
def initial_phonebook():
       rows, cols = int(input("Please enter initial number of contacts")),5
       phone_book = []
       print(phone_book)
       for i in range(rows):
              print("\nEnter contact %d details in following order (only):" %(i+1))
              print("NOTE: + indicates mandatory fields")
              print("...................................................................................................................")
              temp = []
              for j in range(cols):
                  if j ==0:
                         temp.append(str(input("Enter name+: ")))
                         if temp[j] == '' or temp[j] == '':
                               sys.exit(
                                     "Name is a mandatory feild. Procces exiting due to blank"
field...")
                    if j ==1:
                           temp.append(int(input("Enter number+: ")))
automatically
                     if j ==2:
                         temp.append(str(input("Enter e-mail address: ")))
                         if temp[j] == '' or temp[j] == '':
                               temp[j] = None

                    if j ==3:
                         temp.append(str(input("Enter date of birth(dd/nn/yy): ")))
compiler
                         if temp[j] == '' or temp[j] == '':
                               temp[j] = None

                    
                    if j ==4:
                         temp.append(
                               str(input("Enter category(Family/Friends/Work/Other): ")))
compiler
                         if temp[j] == '' or temp[j] == '':
                               temp[j] = None


                phone_book.append(temp)
        print(phone_book)
        return phone_book

def menu():

print("****************************************************")
print("\t\t\tSMARTPHONE DICTIONARY", flush=False)
print("*****************************************************")
print("\tYou can now perform the following operations on this phone book\n")
print("1. Add a new contact")
print("2. Remove an existing contact")
print("")
                            
                               

                        
                    
